# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d7aec875d4e03a429cac83f2a537f6931139cfedc0ea6d7ca7488160091d2b9d53be352c85549559d51ce80e3adcfe9a8dc07b5990f83b7594d215660266d03

test:
  secret_key_base: 334d32fe663654270e31b98374a063db20241316d6eb6fa5c28336e4064ff74b09fc83d75ad845dc15f8ffa6884c81ddb364ade15d9b66792d36fcf30f3ad805

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
